const questions = [
    { number: 1, question: "What is the capital of France?", options: ["Paris", "London", "Rome", "Berlin"] },
    { number: 2, question: "Which planet is known as the Red Planet?", options: ["Mars", "Earth", "Venus", "Jupiter"] },
    { number: 3, question: "Who wrote 'Hamlet'?", options: ["Shakespeare", "Dickens", "Tolstoy", "Hemingway"] },
    { number: 4, question: "What is the largest ocean on Earth?", options: ["Pacific", "Atlantic", "Indian", "Arctic"] },
    { number: 5, question: "What is 5 + 7?", options: ["12", "10", "14", "15"] },
    { number: 6, question: "What gas do plants absorb?", options: ["CO2", "O2", "Nitrogen", "Hydrogen"] },
    { number: 7, question: "Who painted the Mona Lisa?", options: ["Da Vinci", "Van Gogh", "Picasso", "Michelangelo"] },
    { number: 8, question: "What is the boiling point of water?", options: ["100°C", "90°C", "80°C", "120°C"] },
    { number: 9, question: "Which continent is Egypt in?", options: ["Africa", "Asia", "Europe", "Australia"] },
    { number: 10, question: "What is the square root of 144?", options: ["12", "14", "16", "10"] },
    { number: 11, question: "Who discovered gravity?", options: ["Newton", "Einstein", "Galileo", "Curie"] },
    { number: 12, question: "What is the chemical symbol for Gold?", options: ["Au", "Ag", "Fe", "Pb"] },
    { number: 13, question: "Which language is primarily spoken in Brazil?", options: ["Portuguese", "Spanish", "French", "English"] },
    { number: 14, question: "Which organ pumps blood?", options: ["Heart", "Lungs", "Kidney", "Liver"] },
    { number: 15, question: "What is H2O?", options: ["Water", "Oxygen", "Hydrogen", "Salt"] },
    { number: 16, question: "Who is known as the Father of Computers?", options: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"] },
    { number: 17, question: "Which planet is closest to the sun?", options: ["Mercury", "Venus", "Earth", "Mars"] },
    { number: 18, question: "Which country gifted the Statue of Liberty?", options: ["France", "UK", "USA", "Germany"] },
    { number: 19, question: "What is the fastest land animal?", options: ["Cheetah", "Lion", "Tiger", "Horse"] },
    { number: 20, question: "What is the primary gas in the Earth's atmosphere?", options: ["Nitrogen", "Oxygen", "CO2", "Hydrogen"] },
    { number: 21, question: "Who wrote '1984'?", options: ["George Orwell", "Huxley", "Shakespeare", "Tolstoy"] },
    { number: 22, question: "What is the freezing point of water?", options: ["0°C", "100°C", "-10°C", "32°C"] },
    { number: 23, question: "Which instrument measures temperature?", options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"] },
    { number: 24, question: "Which ocean is the smallest?", options: ["Arctic", "Pacific", "Atlantic", "Indian"] },
    { number: 25, question: "What is 9 x 9?", options: ["81", "72", "99", "90"] },
    { number: 26, question: "Who painted Starry Night?", options: ["Van Gogh", "Picasso", "Da Vinci", "Michelangelo"] },
    { number: 27, question: "Which country is famous for sushi?", options: ["Japan", "China", "Thailand", "Korea"] },
    { number: 28, question: "Which is the largest planet?", options: ["Jupiter", "Earth", "Saturn", "Neptune"] },
    { number: 29, question: "Who is the author of Harry Potter?", options: ["J.K. Rowling", "Tolkien", "Lewis", "Martin"] },
    { number: 30, question: "Which metal is liquid at room temperature?", options: ["Mercury", "Gold", "Iron", "Copper"] },
    { number: 31, question: "What is the currency of USA?", options: ["Dollar", "Euro", "Pound", "Yen"] },
    { number: 32, question: "What is the tallest mountain?", options: ["Everest", "K2", "Kangchenjunga", "Lhotse"] },
    { number: 33, question: "Which planet is known for rings?", options: ["Saturn", "Jupiter", "Mars", "Venus"] },
    { number: 34, question: "Which gas do humans breathe in?", options: ["Oxygen", "CO2", "Nitrogen", "Hydrogen"] },
    { number: 35, question: "Who invented the telephone?", options: ["Alexander Graham Bell", "Edison", "Tesla", "Marconi"] }
];

export default questions;
